# Generated by Django 5.1.4 on 2025-03-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examconcours_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examconcours',
            name='slug',
        ),
    ]
