# Generated by Django 5.1.4 on 2025-03-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_examconcours_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examconcours',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
