# Generated by Django 5.1.4 on 2025-03-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eresultats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamations_actives', models.BooleanField(default=True)),
            ],
        ),
    ]
