# Generated by Django 5.1.4 on 2025-03-09 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eresultats', '0002_configsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='niveau_etude',
            field=models.CharField(choices=[('Licence professionnelle 1', 'L1'), ('Licence professionnelle 2', 'L2'), ('Licence professionnelle 3', 'L3'), ('Master professionnelle 1', 'M1'), ('Master professionnelle 2', 'M2')], max_length=30),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Traitée', 'Traitée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eresultats.etudiant')),
            ],
        ),
    ]
